version: "3"

services:
  frontend:
    image: karan060/frontend:latest
    ports: 
      - "5173:5173"
    deploy:
      mode: replicated
      replicas: 1
  backend:
    image: karan060/backend:latest
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1