name: "Build CHAT APP"

on:
    push: 
        branches: 
         - "master"
    pull_request: 

jobs:
    build:
        name: "building docker image"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            
            - name: find and replace backend url in frontend
              uses: jacobtomlinson/gha-find-replace@v3
              with: 
                find: "http://localhost:3001"
                replace: "https://back.karan.meltred.tech"
                include: "frontend/src/**"
                regex: true

            - name: "build image"
              run: |
                docker build -t karan060/frontend:latest -f frontend.Dockerfile .
                docker build -t karan060/backend:latest -f backend.Dockerfile .
            - name: push
              if: github.ref == 'refs/heads/master' 
              run: |
                echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "karan060" --password-stdin
                docker push karan060/frontend:latest
                docker push karan060/backend:latest